# Generated by Django 4.0.2 on 2022-09-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
